os: osx
osx_image: xcode13.1
language: swift
script: xcodebuild clean build test -project coolfinder/Coolfinder.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 12" ONLY_ACTIVE_ARCH=YES
